k8-proxy/glasswall-desktop

README.md, package.json, src/electron/index.ts, src/ui/utils/utils.tsx, static/package.json
Added Cmd/Ctrl Q to quit
Link to Glasswall Desktop in the Release Note section is broken 
Updated ReadME
=> Bugs fixing

static/public/index.html
Integrated Google Analytics to the desktop web portal
=> Integrated google analytics

.gitignore, README.md, package.json, src/electron/index.ts, src/ui/views/RebuildFiles.tsx, static/package.json, static/src/components/Demo.jsx
1.  Fixed Video link
2. Fixed Help Shortcut
4. Updated ReadMe for new version
=> Video link and Google Analytics

src/ui/views/RebuildFiles.tsx
Rebuild App: Pagination is not working properly on desktop app #7
=> Fix for pagination issue on Dektop App

.github/workflows/build.yml, README.md
Fixed the issue with the Linux release of the app
=> Fixed the issue with the Linux release of the app

package.json, src/ui/views/DockerRebuildFiles.tsx
UI option for Output filesystem as Flat/Hierarchy is not updated on docker based rebuild files #98
=> UI option for Output filesystem as Flat/Hierarchy is not updated on  docker based rebuild files

.gitignore, src/ui/components/DockerUtils.tsx, src/ui/index.tsx, src/ui/utils/utils.tsx, src/ui/views/DockerRebuildFiles.tsx
=> File analysis with docker 

README.md, package.json, src/ui/utils/utils.tsx, static/package.json
Major Features
Processing rebuild locally through Docker after pulling the docker image.
Creating analysis report for rebuilt files locally through Docker.
Added option for User to rebuild app either locally or through cloud.
=> Release version updaed

src/ui/components/HealthCheckStatus.tsx, src/ui/utils/utils.tsx, src/ui/views/DockerConfiguration.tsx, src/ui/views/DockerRebuildFiles.tsx
=> Health check changes

src/ui/components/DockerUtils.tsx, src/ui/views/DockerConfiguration.tsx
Fixed the issue related to the Docker Status when docker is not installed
=> Docker_Status_Fix

src/ui/components/DockerUtils.tsx, src/ui/index.tsx, src/ui/views/DockerConfiguration.tsx, src/ui/views/DockerRebuildFiles.tsx
Update UI on PULL image success
Stops loader 
redirect to configuration screen when health checks failed
=> Fixed Bugs

src/ui/utils/utils.tsx
Changed the new docker image id
=> Docker_Image_ID_Change

README.md, package.json, src/ui/components/DockerUtils.tsx, src/ui/utils/utils.tsx, src/ui/views/DockerConfiguration.tsx, src/ui/views/DockerRebuildFiles.tsx, src/ui/views/RebuildFiles.tsx, static/package.json
1. Local rebuild health check : To check the local rebuild configuration and it state
A. If docker Installed.
B. If docker running.
C. If GW image present else pull.
D. If GW image licensed.
2. Health check event logging:  Added the event logs for docker health check.
3. Rebuild & File analysis event logging:  Added the event logs for local Rebuild and file analysis.
4. Added health check functionality on UI.
5. Made output path persistent across rebuilds.
6. UI Enhancement and some minor fixes
=> Release changes

src/ui/utils/utils.tsx, src/ui/views/DockerConfiguration.tsx, src/ui/views/HomePage.tsx
Loader issue fixed when pull image failed
=> Loader issue fixed when pull image failed

src/ui/components/DockerUtils.tsx
Backend change for Docker image license check for re-download
=> docker-image-license-checking

src/ui/components/DockerUtils.tsx, src/ui/components/FileUploadUtils.tsx, src/ui/components/HealthCheckStatus.tsx, src/ui/components/SerialDocker.tsx, src/ui/components/SideDrawer.tsx, src/ui/index.html, src/ui/utils/utils.tsx, src/ui/views/DockerConfiguration.tsx, src/ui/views/DockerRebuildFiles.tsx, src/ui/views/HomePage.tsx, src/ui/views/LoggerView.tsx, src/ui/views/RebuildFiles.tsx
Sequential-Parallel docker UI and bakend Integration + Logger tab integration
=> Sequential-Parallel docker UI and bakend Integration + Logger tab integration

src/ui/utils/utils.tsx, src/ui/views/DockerRebuildFiles.tsx, src/ui/views/RebuildFiles.tsx
Updated Metadata to add cloud/doker rebuild
=> Updated Metadata to add cloud/doker rebuild

static/public/index.html, static/src/utils/utils.js
GA id changed in the static site
=> GA_ID_Change

package-lock.json, package.json, src/ui/components/ThreatIntelligence.tsx, src/ui/utils/utils.tsx, src/ui/views/DockerRebuildFiles.tsx
Threat intelligence reporting added
=> Threat intelligence reporting

src/ui/components/DockerUtils.tsx, src/ui/components/SideDrawer.tsx, src/ui/index.tsx, src/ui/views/DockerRebuildFiles.tsx, src/ui/views/Sessions.tsx
On clicking the browse button and then clicking on cancel button the target folder path becomes empty
Threat level color coding
=> Feature enhancements 

src/ui/components/ThreatIntelligence.tsx, src/ui/utils/utils.tsx, src/ui/views/DockerConfiguration.tsx, src/ui/views/LoggerView.tsx
File based logger, Added license check after pull image
=> File based logger, Added license check after pull image

src/ui/components/Info.tsx, src/ui/components/SessionsUtils.tsx, src/ui/components/SideDrawer.tsx, src/ui/views/DockerRebuildFiles.tsx, src/ui/views/Sessions.tsx
=> Sessions Feature changes 

src/ui/utils/utils.tsx, src/ui/views/DockerRebuildFiles.tsx
Fixed extra column in redbuild docker
=> Fixed extra column in redbuild docker

src/ui/components/FileUploadUtils.tsx, src/ui/components/SerialDocker.tsx, src/ui/utils/utils.tsx, src/ui/views/Sessions.tsx, src/ui/views/settings.tsx
=> Settings and session changes

src/ui/views/Sessions.tsx
=> Removed clear buton

README.md, package.json, src/ui/utils/utils.tsx, static/package.json
Modified the release version in the package and ReadMe
=> Modified-build-version-and-readme

src/ui/utils/utils.tsx, src/ui/views/DockerRebuildFiles.tsx, src/ui/views/RebuildFiles.tsx
On clicking the browse button and then clicking on the cancel button the target folder path becomes empty 
Default target folder directory should be set
=> Fixed Bugs 

src/ui/components/DockerUtils.tsx, src/ui/components/SerialDocker.tsx, src/ui/utils/utils.tsx, src/ui/views/DockerRebuildFiles.tsx
=> Improved-logging-performance

src/ui/views/RebuildPolicy.tsx
Added event handlder for policy items
=> Added event handlder for policy items

src/ui/components/DockerUtils.tsx, src/ui/components/SerialDocker.tsx, src/ui/index.tsx, src/ui/utils/utils.tsx, src/ui/views/RebuildPolicy.tsx
Policy Management UI and Backend Integration
=> Policy Management Backend Integration

src/ui/components/FileAnalysis/FileAnalysis.css, src/ui/components/FileAnalysis/FileAnalysis.tsx, src/ui/components/FileAnalysis/FileAttributes.tsx, src/ui/components/FileAnalysis/Item.tsx, src/ui/components/FileAnalysis/Items.tsx, src/ui/components/FileAnalysis/RenderAnalysis.tsx, src/ui/components/FileAnalysis/ThreatAnalysis.tsx, src/ui/components/ThreatAnalysisDialog.tsx, src/ui/utils/utils.tsx, src/ui/views/DockerRebuildFiles.tsx
=> Threat Analysis Changes

src/ui/utils/utils.tsx
=> LogFile-UI-Changed

package-lock.json, package.json, src/ui/views/RebuildPolicy.tsx, src/ui/views/Sessions.tsx
Report Analysis UI integration and Icon changes in session
=> Icon-change-Analysis-report

README.md, package-lock.json, package.json, src/ui/utils/utils.tsx, static/package.json
Changes in ReadMe and packages part of release.
=> Release-changes

src/ui/utils/utils.tsx
Updated Release Notes UI version
=> Updated Release Notes UI version

src/ui/utils/utils.tsx, src/ui/views/DockerConfiguration.tsx, src/ui/views/DockerRebuildFiles.tsx, src/ui/views/LoggerView.tsx, src/ui/views/RebuildFiles.tsx, src/ui/views/RebuildPolicy.tsx, src/ui/views/Sessions.tsx, src/ui/views/settings.tsx
=> UI changes

src/ui/views/RebuildPolicy.tsx, static/src/css/styles.css
Responsive and Rebuild Policy unsaved icon
=> Responsive and Rebuild Policy unsaved icon

src/ui/components/DockerUtils.tsx, src/ui/components/SerialDocker.tsx, src/ui/utils/utils.tsx, src/ui/views/DockerConfiguration.tsx, src/ui/views/RebuildFiles.tsx, src/ui/views/settings.tsx
Threat Analysis for cloud rebuild UI Implementation
To add the ability to the customer the name of the docker image to use
=> Ability to the customer the name of the docker image to use

src/electron/index.ts, src/ui/views/RebuildPolicy.tsx
=> Updated rebuild policy

src/electron/index.ts
=> App Icon changed

src/ui/views/RebuildFiles.tsx, src/ui/views/settings.tsx
Added threat level in cloud rebuild
=> Added threat level in cloud rebuild

src/ui/views/DockerRebuildFiles.tsx, src/ui/views/RebuildPolicy.tsx
=> Fixed Rebuild policy

src/ui/components/SideDrawer.tsx, src/ui/views/RebuildPolicy.tsx
=> Unsaved policy dialog

package.json, src/ui/utils/utils.tsx, static/package.json, static/src/components/Header.jsx
Release Changes
1. Added Threat Intelligence to the cloud rebuild, Displayed threat level on the UI
2. Watermark added for rebuild PDF file.
3. Buy Token feature added under setting.
4. Bugs Fixes:
- On rebuilding the file using Cloud user is displayed the wrong time under session.
- Fixed sorting in-case of multi page
- Fixed alignment under session page.
- Fixed analysis report earlier it was showing High for all the files.
- Error message being displayed incase file is blocked due to Policy.
- Fixed alignment on mouse hover on Flat and Hierarchy label on Cloud and Docker page
- Session page not getting loaded in case no session is present.
- Raw Logs added in multi-line format in case logs are very long. (Removed horizontal scroll bar)
- Color of all the buttons under different pages …
=> Release push changes

package.json, src/ui/utils/utils.tsx, static/package.json, static/src/components/Header.jsx
=> Verion changes

src/ui/components/FileUploadUtils.tsx, src/ui/views/RebuildFiles.tsx
Re-ordered the API call for Analysis and rebuild file
=> API_Reorder_Cloud

src/ui/views/DockerRebuildFiles.tsx
=> Docker_Page_Issue_Fix

src/electron/index.ts
=> Fixed Crash

src/ui/components/FileUploadUtils.tsx, src/ui/utils/utils.tsx
Cloud_Policy_validation_in_case_of_policy_disallow
=> Cloud_Policy_Validation_Check

src/ui/components/DockerUtils.tsx, src/ui/utils/utils.tsx, src/ui/views/DockerRebuildFiles.tsx, src/ui/views/PastRebuildPolicy.tsx, src/ui/views/RebuildPolicy.tsx
Rebuild Docker: Saving the rebuilt file through link to custom location the file get corrupt. #302
=> Fixed an issue and updated Rebuild image Tag

src/ui/components/FileUploadUtils.tsx
=> Cloud_Analysis_IssueFix

src/ui/components/FileUploadUtils.tsx, src/ui/components/Navbar.tsx, src/ui/views/DockerRebuildFiles.tsx, src/ui/views/RebuildFiles.tsx
=> Ui Changes and fixes

src/ui/assets/style/style.css, src/ui/views/settings.tsx
Cloud Configuration should allow only HTTPs URL
=> Cloud Configuration should allow only HTTPs URL

src/electron/index.ts, src/ui/components/Footer.tsx, src/ui/views/DockerConfiguration.tsx, src/ui/views/DockerRebuildFiles.tsx, src/ui/views/HomePage.tsx, src/ui/views/PastRebuildPolicy.tsx, src/ui/views/RebuildFiles.tsx, src/ui/views/RebuildPolicy.tsx, src/ui/views/ReleaseNote.tsx, src/ui/views/Sessions.tsx, src/ui/views/settings.tsx
=> Footer issue fixes

src/ui/views/settings.tsx
=> fixed https handling issue

jest.config.js, jest.setup.js, package-lock.json, package.json, src/electron/index.ts, static/src/App.test.js, tests/TestUtils.js, tests/index.test.js, tsconfig.json
Added Intial Unit Test for Utils file
=> Added Intial Unit Test for Utils file

.gitignore, jest.config.js, package-lock.json, package.json
Added Code coverage in HTML format
https://github.com/k8-proxy/glasswall-desktop/issues/370
=> Added Code coverage in HTML format

src/ui/components/DockerUtils.tsx
=> Display_Docker_Image_Version

src/__tests__/docker.utils.test.tsx, src/__tests__/serialdocker.utils.test.tsx, src/ui/components/DockerUtils.tsx, src/ui/components/HealthCheckStatus.tsx, src/ui/components/SerialDocker.tsx, src/ui/utils/utils.tsx, src/ui/views/DockerRebuildFiles.tsx, src/ui/views/settings.tsx
Added more tests and cli version through settings
=> Added more tests and cli version through settings

jest.config.js, package-lock.json, package.json, src/__tests__/__snapshots__/logs.test.tsx.snap, src/__tests__/logs.test.tsx, src/__tests__/serialdocker.utils.test.tsx, src/__tests__/sessions.utils.test.tsx, src/__tests__/utils.test.tsx, src/globals.d.ts, src/ui/components/SessionsUtils.tsx
=> Added snapshot tests

wallaby.js
Updated wallby.js runner to Node
=> Updated wallby.js runner to Node

.github/workflows/build.yml, src/__tests__/utils/rebuild.test.tsx, src/__tests__/views/dockerConfiguration.test.tsx, src/__tests__/views/dockerRebuildFiles.test.tsx, src/__tests__/views/homePage.test.tsx, src/__tests__/views/pastRebuildPolicy.test.tsx, src/__tests__/views/rebuildFiles.test.tsx, src/__tests__/views/rebuildPolicy.test.tsx, src/__tests__/views/sessions.test.tsx, src/__tests__/views/settings.test.tsx, src/ui/services/PolicyService.tsx, src/ui/utils/utils.tsx, src/ui/views/settings.tsx
=> Fixed tests

.github/workflows/build.yml, package.json, src/__tests__/_longrun_tests_/services/dockerService.longrun.test.tsx, src/__tests__/components/footer.test.tsx, src/__tests__/components/healthCheckStatus.test.tsx, src/__tests__/components/loader.test.tsx, src/__tests__/components/modalContent.test.tsx, src/__tests__/components/navbar.test.tsx, src/__tests__/components/popupBtn.test.tsx, src/__tests__/components/rawXml.test.tsx, src/__tests__/components/releaseNote.test.tsx, src/__tests__/components/sideDrawer.test.tsx, src/__tests__/components/threatAnalysisDialog.test.tsx, src/__tests__/components/webFrameView.test.tsx, src/__tests__/services/dockerService.test.tsx, src/__tests__/services/rebuildSessionService.test.tsx, src/__tests__/utils/rebuild.test.tsx, src/__tests__/views/welcomePage.test.tsx, src/ui/components/SideDrawer.tsx, src/ui/services/GWSerialDockerService.tsx, src/ui/services/LoggerService.tsx, src/ui/services/PolicyService.tsx, src/ui/services/RebuildSessionsService.tsx, src/ui/utils/RebuildUtils.tsx, src/ui/utils/utils.tsx, src/ui/views/PastRebuildPolicy.tsx, src/ui/views/RebuildPolicy.tsx, src/ui/views/Sessions.tsx, wallaby-longrun.js
Removed console logs and fixed tests
=> Removed console logs and fixed tests

src/__tests__/_longrun_tests_/services/dockerService.longrun.test.tsx, src/__tests__/services/dockerService.test.tsx, src/__tests__/utils/rebuild.test.tsx, src/__tests__/utils/utils.test.tsx
=> newly added test cases

jest.config.js, package.json, src/setupTests.js, src/ui/services/GWDockerService.tsx, src/ui/views/RebuildPolicy.tsx, wallaby.js
=> Added more tests

jest.config.js, package.json
Updated tests configuration files
=> Updated tests configuration files

src/ui/utils/utils.tsx, src/ui/views/DockerRebuildFiles.tsx, src/ui/views/RebuildFiles.tsx
Moved duplicate function to utils
=> Moved duplicate function to utils

.github/workflows/build.yml, package.json, src/setupTests.js, src/ui/services/LoggerService.tsx, src/ui/utils/utils.tsx, src/ui/views/DockerRebuildFiles.tsx, src/ui/views/RebuildFiles.tsx
=> Added setuptests.js

src/__tests__/services/rebuildSessionService.test.tsx
=> removed test cases

package-lock.json, src/electron/index.ts, src/ui/utils/RebuildUtils.tsx, src/ui/views/settings.tsx
1. Fixed copy/past/cut issue on Mac
2. Added suppot for both http and https
=> CR and Fixed issues

src/__tests__/services/cloudRebuildService.test.tsx, src/ui/services/GWCloudRebuildService.tsx, src/ui/utils/utils.tsx, src/ui/views/RebuildFiles.tsx, src/ui/views/settings.tsx
Fixed large file issue and settings page hang issue
=> Fixed large file issue and settings page hang issue
